// authentication-system-react/src/components/dashboard/Sidebar.jsx
import React from "react";
import useAuth from "../../hooks/useAuth";
import { NavLink } from "react-router-dom";

export default function Sidebar() {
  const { logout } = useAuth();
  const navLinks = [
    { name: "Dashboard", path: "/dashboard", icon: "home" },
    { name: "Products", path: "/dashboard/product", icon: "products" },
    { name: "Upload Files", path: "/dashboard/upload", icon: "upload" },
  ];

  // Simple icon renderer (you might want to use a proper icon library)
  const renderIcon = (iconName) => {
    switch (iconName) {
      case "home":
        return (
          <svg
            className="w-5 h-5"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"
            ></path>
          </svg>
        );
      case "products":
        return (
          <svg
            className="w-5 h-5"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d="M16 11V7a4 4 0 00-8 0v4M5 11h14l1 9H4l1-9z"
            ></path>
          </svg>
        );

      case "upload":
        return (
          <svg
            className="w-5 h-5"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1M16 7l-4-4m0 0L8 7m4-4v12"
            ></path>
          </svg>
        );
      default:
        return null;
    }
  };
  return (
    <div className="w-64 bg-indigo-800 text-white flex flex-col">
      <div className="p-4 border-b border-indigo-700">
        <div className="flex items-center">
          <img
            src="/src/assets/ensetLogo.png"
            alt="Logo"
            className="h-8 w-auto"
          />
          <span className="ml-2 text-lg font-bold">Authentication System</span>
        </div>
      </div>

      <nav className="flex-1 overflow-y-auto">
        <ul className="py-4">
          {navLinks.map((link, index) => (
            <li key={index}>
              <NavLink
                to={link.path}
                className={({ isActive }) =>
                  `flex items-center px-6 py-3 hover:bg-indigo-700 ${
                    isActive ? "bg-indigo-700" : ""
                  }`
                }
                end={link.path === "/dashboard"}
              >
                <span className="mr-3">{renderIcon(link.icon)}</span>
                {link.name}
              </NavLink>
            </li>
          ))}
        </ul>
      </nav>

      <div className="p-4 border-t border-indigo-700">
        <button
          onClick={logout}
          className="flex items-center w-full px-4 py-2 rounded-md hover:bg-indigo-700"
        >
          <svg
            className="w-5 h-5 mr-3"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"
            ></path>
          </svg>
          Sign Out
        </button>
      </div>
    </div>
  );
}

// authentication-system-angular/src/app/components/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from '../../services/auth.service';
import { User } from '../../models/user.model';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
})
export class SidebarComponent implements OnInit {
  currentUser: User | null = null;

  constructor(private authService: AuthService) {}

  ngOnInit(): void {
    this.authService.currentUser$.subscribe((user) => {
      this.currentUser = user;
    });
  }

  logout(): void {
    this.authService.logout();
  }
}

<div
  class="bg-gradient-to-b from-indigo-800 to-indigo-900 h-full min-h-screen w-72 text-white py-6 px-6 flex flex-col shadow-xl"
>
  <!-- Logo and App Name -->
  <div class="flex items-center space-x-3 mb-10 px-2">
    <img
      src="../../assets/ensetLogo.png"
      alt="ENSET Logo"
      class="h-11 w-auto"
    />
    <div class="text-lg font-bold tracking-tight">Authentication System</div>
  </div>

  <!-- Navigation Links -->
  <nav class="flex-1">
    <div
      class="text-xs font-semibold text-indigo-200 uppercase tracking-wider mb-3 px-3"
    >
      Main Menu
    </div>
    <ul class="space-y-1">
      <li>
        <a
          routerLink="/dashboard"
          routerLinkActive="bg-indigo-700 text-white font-medium"
          class="flex items-center space-x-3 px-4 py-3 rounded-lg hover:bg-indigo-700 transition-all duration-200 group"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-5 w-5 text-indigo-200 group-hover:text-white"
            viewBox="0 0 20 20"
            fill="currentColor"
          >
            <path
              d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z"
            />
          </svg>
          <span>Dashboard</span>
        </a>
      </li>
      <li>
        <a
          routerLink="/products"
          routerLinkActive="bg-indigo-700 text-white font-medium"
          class="flex items-center space-x-3 px-4 py-3 rounded-lg hover:bg-indigo-700 transition-all duration-200 group"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-5 w-5 text-indigo-200 group-hover:text-white"
            viewBox="0 0 20 20"
            fill="currentColor"
          >
            <path d="M4 3a2 2 0 100 4h12a2 2 0 100-4H4z" />
            <path
              fill-rule="evenodd"
              d="M3 8h14v7a2 2 0 01-2 2H5a2 2 0 01-2-2V8zm5 3a1 1 0 011-1h2a1 1 0 110 2H9a1 1 0 01-1-1z"
              clip-rule="evenodd"
            />
          </svg>
          <span>Products</span>
        </a>
      </li>
      <li>
        <a
          routerLink="/files"
          routerLinkActive="bg-indigo-700 text-white font-medium"
          class="flex items-center space-x-3 px-4 py-3 rounded-lg hover:bg-indigo-700 transition-all duration-200 group"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-5 w-5 text-indigo-200 group-hover:text-white"
            viewBox="0 0 20 20"
            fill="currentColor"
          >
            <path
              fill-rule="evenodd"
              d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM6.293 6.707a1 1 0 010-1.414l3-3a1 1 0 011.414 0l3 3a1 1 0 01-1.414 1.414L11 5.414V13a1 1 0 11-2 0V5.414L7.707 6.707a1 1 0 01-1.414 0z"
              clip-rule="evenodd"
            />
          </svg>
          <span>Upload Files</span>
        </a>
      </li>
    </ul>
  </nav>

  <!-- Logout Button -->
  <div class="pt-4 border-t border-indigo-700">
    <button
      (click)="logout()"
      class="w-full flex items-center justify-center space-x-3 px-4 py-3 rounded-lg bg-indigo-700 hover:bg-indigo-600 transition-all duration-200"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="h-5 w-5"
        viewBox="0 0 20 20"
        fill="currentColor"
      >
        <path
          fill-rule="evenodd"
          d="M3 3a1 1 0 00-1 1v12a1 1 0 102 0V4a1 1 0 00-1-1zm10.293 9.293a1 1 0 001.414 1.414l3-3a1 1 0 000-1.414l-3-3a1 1 0 10-1.414 1.414L14.586 9H7a1 1 0 100 2h7.586l-1.293 1.293z"
          clip-rule="evenodd"
        />
      </svg>
      <span>Sign Out</span>
    </button>
  </div>
</div>
